variable "ami" {}
variable "instance-type" {}
variable "security-group-webserver" {}
variable "security-group-database" {}
variable "db-private-subnet" {}
variable "private-subnet" {}
variable "public-subnet" {}
variable "key-name" {}
variable "ssh-key-file" {}
#variable "run-script" {}